version: '2'
services:
  ruby:
    image: ruby:3.2-alpine@sha256:ee39ade2cbda43fd466d787a595f142c9fa318284dd1d6b3e2f9590a9f4f75ab
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"